import mongoose from 'mongoose';
import { randomUUID } from 'node:crypto';
import { config } from './config.js';
import { decryptSecret, encryptSecret, maskSecret } from './secrets.js';

export type Channel = 'sms' | 'email';
export type UserRole = 'customer' | 'manager' | 'admin' | 'super_admin' | 'support' | 'content_manager' | 'finance';
export type User = { id: string; phone?: string; email?: string; fullName?: string; avatarUrl?: string; avatarMediaId?: string; lastLoginAt?: string; lastLoginIp?: string; marketingEmailOptIn?: boolean; marketingSmsOptIn?: boolean; marketingInAppOptIn?: boolean; status: 'active' | 'blocked' | 'pending'; role: UserRole; createdAt: string; updatedAt: string };
export type ServiceStatus = 'active' | 'hidden' | 'maintenance' | 'archived';
export type ServiceKey = 'flights' | 'hotels' | 'homes' | 'visa' | 'tours' | 'esim';
export type Tour = { id: string; slug: string; title: string; country: string; tourType: string; destinations: string[]; durationDays: number; durationNights: number; description: string; imageUrl: string; mediaId?: string; metadata: Record<string, unknown>; priceBdt: number; status: 'draft' | 'published' | 'archived'; featured: boolean; createdBy?: string; createdAt: string; updatedAt: string };
export type TourFilters = { q?: string; country?: string; tourType?: string; status?: Tour['status'] | 'all'; maxPrice?: number; sort?: 'newest' | 'price_asc' | 'price_desc' };
export type CreateTour = Omit<Tour, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateTour = Partial<Omit<CreateTour, 'createdBy'>>;
export type OtpChallenge = { id: string; identity: string; channel: Channel; codeHash: string; attempts: number; maxAttempts: number; expiresAt: string; consumedAt?: string; requestIp?: string; purpose?: string; userId?: string; targetIdentity?: string; createdAt: string };
export type Session = { id: string; userId: string; refreshJti: string; userAgent?: string; ip?: string; expiresAt: string; revokedAt?: string; createdAt: string };
export type BookingStatus = 'new' | 'reviewing' | 'accepted' | 'processing' | 'pending' | 'confirmed' | 'completed' | 'rejected' | 'cancelled' | 'failed';
export type Booking = { id: string; userId: string; vertical: 'flight' | 'hotel' | 'home' | 'visa' | 'esim' | 'tour'; status: BookingStatus; providerRef?: string; ownerId?: string; internalNote?: string; request: unknown; response?: unknown; createdAt: string; updatedAt: string };
export type BookingEvent = { id: string; bookingId: string; actorId?: string; action: string; fromStatus?: BookingStatus; toStatus?: BookingStatus; note?: string; createdAt: string };
export type AdminBooking = Booking & { customer?: User; owner?: User };
export type AdminBookingFilters = { q?: string; status?: BookingStatus | 'needs_review' | 'all'; vertical?: Booking['vertical'] | 'all'; ownerId?: string; page?: number; pageSize?: number };
export type PaymentStatus = 'created' | 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded';
export type Payment = { id: string; bookingId: string; userId: string; provider: string; amount: number; currency: string; status: PaymentStatus; transactionRef?: string; providerPayload?: unknown; createdAt: string; updatedAt: string };
export type AdminPayment = Payment & { customer?: User; booking?: Booking };
export type SupportStatus = 'open' | 'pending' | 'in_progress' | 'waiting_customer' | 'resolved' | 'closed';
export type SupportPriority = 'low' | 'normal' | 'high' | 'urgent';
export type SupportTicket = { id: string; userId?: string; name: string; mobile: string; email: string; subject: string; status: SupportStatus; priority: SupportPriority; assignedTo?: string; assignedToName?: string; createdAt: string; updatedAt: string };
export type SupportMessage = { id: string; ticketId: string; authorId?: string; authorType: 'customer' | 'admin' | 'system'; message: string; internal: boolean; createdAt: string };
export type NotificationStatus = 'queued' | 'sent' | 'failed' | 'read';
export type Notification = { id: string; userId: string; title: string; message: string; channels: ('in_app' | 'sms' | 'email')[]; status: NotificationStatus; readAt?: string; sentAt?: string; failureReason?: string; createdBy?: string; createdAt: string };
export type AdminSetting = { key: string; value?: string; configured: boolean; masked?: string; secret: boolean; updatedBy?: string; updatedAt?: string };
export type ServiceVisibility = { key: ServiceKey; label: string; icon: string; status: ServiceStatus; updatedBy?: string; updatedAt?: string };
export type MediaStatus = 'active' | 'archived' | 'failed';
export type MediaAsset = { id: string; publicId: string; secureUrl: string; originalFilename: string; mimeType: string; format: string; width?: number; height?: number; bytes: number; folder: string; altText?: string; uploadedBy?: string; status: MediaStatus; createdAt: string; updatedAt: string };
export type AdminNavItem = { id: string; groupName: string; parentId?: string; label: string; route: string; icon: string; permission?: string; sortOrder: number; visible: boolean; enabled: boolean; createdAt: string; updatedAt: string };
export type CreateNavItem = Omit<AdminNavItem, 'id' | 'createdAt' | 'updatedAt'>;
export type UpdateNavItem = Partial<Omit<CreateNavItem, 'createdBy'>>;
export type TravelAgentStatus = 'active' | 'hidden' | 'archived';
export type TravelAgent = { id: string; fullName: string; agencyName?: string; photoUrl?: string; photoPublicId?: string; mediaId?: string; jobTitle?: string; department?: string; phone?: string; whatsapp?: string; email?: string; officeLocation?: string; city?: string; shortBio?: string; fullDescription?: string; languages: string[]; experienceYears?: number; specialization?: string; workingHours?: string; status: TravelAgentStatus; featured: boolean; displayOrder: number; createdBy?: string; updatedBy?: string; createdAt: string; updatedAt: string };
export type CampaignChannel = 'email' | 'sms' | 'in_app';
export type CampaignStatus = 'draft' | 'scheduled' | 'queued' | 'processing' | 'completed' | 'partially_failed' | 'failed' | 'cancelled' | 'archived';
export type Campaign = { id: string; name: string; title?: string; description?: string; imageUrl?: string; imagePublicId?: string; imageMediaId?: string; cta?: string; ctaUrl?: string; startDate?: string; endDate?: string; channels: CampaignChannel[]; status: CampaignStatus; subject?: string; preheader?: string; senderName?: string; senderEmail?: string; emailHtml?: string; emailText?: string; smsMessage?: string; webTitle?: string; webMessage?: string; webCtaText?: string; webCtaUrl?: string; segmentId?: string; recipientFilter: Record<string, unknown>; scheduledAt?: string; timezone?: string; totalRecipients: number; queuedCount: number; sentCount: number; deliveredCount: number; failedCount: number; readCount: number; createdBy?: string; createdAt: string; updatedAt: string };
export type CampaignRecipient = { id: string; campaignId: string; userId: string; channel: CampaignChannel; status: 'queued' | 'processing' | 'sent' | 'delivered' | 'failed' | 'read' | 'unsubscribed'; providerRef?: string; error?: string; attempts: number; queuedAt?: string; sentAt?: string; deliveredAt?: string; readAt?: string; createdAt: string };
export type CampaignTemplate = { id: string; name: string; type: CampaignChannel; subject?: string; content: string; metadata: Record<string, unknown>; status: 'active' | 'archived'; createdBy?: string; createdAt: string; updatedAt: string };
export type CustomerSegment = { id: string; name: string; description?: string; rules: Record<string, unknown>; status: 'active' | 'archived'; createdBy?: string; createdAt: string; updatedAt: string };
export type CreateCampaign = Omit<Campaign,'id'|'totalRecipients'|'queuedCount'|'sentCount'|'deliveredCount'|'failedCount'|'readCount'|'createdAt'|'updatedAt'> & { createdBy?: string };
export type UpdateCampaign = Partial<Omit<CreateCampaign,'createdBy'>>;
export type CampaignQueueItem = CampaignRecipient & { recipient?: User; campaign?: Campaign };
export type SettingPatch = Record<string, string | undefined>;
export type ContentType = 'homepage' | 'destination' | 'hotel' | 'home' | 'visa' | 'esim' | 'offer' | 'airline' | 'banner' | 'faq' | 'company' | 'umrah_fare' | 'umrah_package' | 'holiday_package' | 'medical_tourism' | 'card_offer' | 'airline_offer' | 'explore' | 'app';
export type ContentStatus = 'draft' | 'published' | 'archived';
export type ContentItem = { id: string; type: ContentType; slug: string; title: string; subtitle?: string; description?: string; imageUrl?: string; mediaId?: string; metadata: Record<string, unknown>; status: ContentStatus; sortOrder: number; createdBy?: string; createdAt: string; updatedAt: string };
export type ContentFilters = { type?: ContentType | 'all'; status?: ContentStatus | 'all'; q?: string; includeArchived?: boolean };

export type AdminStats = { bookings: { total: number; new: number; reviewing: number; accepted: number; processing: number; pending: number; confirmed: number; completed: number; rejected: number; cancelled: number; failed: number }; verticalCounts: Record<Booking['vertical'], number>; revenueBdt: number; revenueTrend: Array<{ month: string; revenueBdt: number; payments: number }>; customers: number; tours: { total: number; published: number; draft: number; archived: number }; supportTickets: { total: number; open: number; pending: number; inProgress: number; waitingCustomer: number; resolved: number; closed: number }; statusDistribution: Array<{ status: BookingStatus; count: number }> };
export type AdminCustomer = User & { totalBookings: number; totalSpentBdt: number; lastActivity?: string };
export type AdminCustomerDetail = AdminCustomer & { bookings: Booking[]; payments: Payment[]; notifications: Notification[]; supportTickets: SupportTicket[]; notes: CustomerNote[] };
export type CustomerNote = { id: string; userId: string; authorId?: string; note: string; createdAt: string };
export type AdminNotification = Notification & { recipient?: User; createdByUser?: User };
export type AdminAuditLog = { id: number; action: string; userId?: string; admin?: User; ip?: string; metadata: unknown; createdAt: string };

type CreateUser = { identity: string; channel: Channel; fullName?: string; role?: User['role'] };
type CreateOtp = Omit<OtpChallenge, 'createdAt'>;
type CreateSession = Omit<Session, 'createdAt'>;
type CreateBooking = { userId: string; vertical: Booking['vertical']; request: unknown; status?: BookingStatus };
type CreatePayment = { bookingId: string; userId: string; provider: string; amount: number; currency: string; status?: Payment['status'] };
type CreateTicket = Omit<SupportTicket, 'id' | 'createdAt' | 'updatedAt' | 'status' | 'priority' | 'assignedTo'> & { status?: SupportTicket['status']; priority?: SupportPriority; assignedTo?: string };
type CreateNotification = Omit<Notification, 'id' | 'createdAt' | 'status' | 'sentAt' | 'failureReason' | 'createdBy'> & { status?: NotificationStatus; sentAt?: string; failureReason?: string; createdBy?: string };
type CreateContent = Omit<ContentItem, 'id' | 'createdAt' | 'updatedAt'>;
type UpdateContent = Partial<Omit<CreateContent, 'createdBy'>>;
type CreateMediaAsset = Omit<MediaAsset, 'id' | 'createdAt' | 'updatedAt'>;

export interface Store {
  health(): Promise<boolean>; close(): void;
  listNavigation(visibleOnly?: boolean): Promise<AdminNavItem[]>; createNavigation(input: CreateNavItem): Promise<AdminNavItem>; updateNavigation(id: string, patch: UpdateNavItem): Promise<AdminNavItem | undefined>; deleteNavigation(id: string): Promise<boolean>; reorderNavigation(ids: string[]): Promise<void>;
  findUserByIdentity(identity: string): Promise<User | undefined>; getPasswordHash(identity: string): Promise<string | undefined>; setPasswordHash(id: string, hash: string): Promise<void>; findUserById(id: string): Promise<User | undefined>; updateUserProfile(id: string, patch: { fullName?: string; email?: string; phone?: string; avatarUrl?: string; avatarMediaId?: string; marketingEmailOptIn?: boolean; marketingSmsOptIn?: boolean; marketingInAppOptIn?: boolean }): Promise<User | undefined>; updateLastLogin(id: string, ip?: string): Promise<void>; listSessions(userId: string): Promise<Session[]>; revokeOtherSessions(userId: string, keepSessionId: string): Promise<void>; listUsers(): Promise<User[]>; createUser(input: CreateUser): Promise<User>; setUserRole(id: string, role: User['role']): Promise<User | undefined>; listAdminCustomers(filters?: { q?: string; status?: User['status'] | 'all'; page?: number; pageSize?: number }): Promise<{ customers: AdminCustomer[]; total: number; page: number; pageSize: number; pageCount: number }>; findAdminCustomer(id: string): Promise<AdminCustomerDetail | undefined>; addCustomerNote(input: { userId: string; authorId: string; note: string }): Promise<CustomerNote>; listCustomerNotes(userId: string): Promise<CustomerNote[]>;
  createOtp(input: CreateOtp): Promise<OtpChallenge>; findOtp(id: string): Promise<OtpChallenge | undefined>; incrementOtpAttempts(id: string): Promise<OtpChallenge | undefined>; consumeOtp(id: string): Promise<void>; countRecentOtpRequests(identity: string, since: Date): Promise<number>;
  createSession(input: CreateSession): Promise<Session>; findSessionById(id: string): Promise<Session | undefined>; findSessionByRefreshJti(jti: string): Promise<Session | undefined>; revokeSession(id: string): Promise<void>;
  createBooking(input: CreateBooking): Promise<Booking>; updateBooking(id: string, patch: Partial<Pick<Booking, 'status' | 'providerRef' | 'response' | 'internalNote'>>): Promise<Booking | undefined>; findBooking(id: string, userId?: string): Promise<Booking | undefined>; findBookingForTracking(id: string, identity: string): Promise<Booking | undefined>; listBookings(userId: string): Promise<Booking[]>;
  listAdminBookings(filters?: AdminBookingFilters): Promise<{ bookings: AdminBooking[]; total: number; page: number; pageSize: number; pageCount: number }>;
  claimBooking(id: string, userId: string): Promise<AdminBooking | undefined>; releaseBooking(id: string, userId: string, canReleaseAny?: boolean): Promise<AdminBooking | undefined>; updateAdminBooking(id: string, patch: { status?: BookingStatus; internalNote?: string; ownerId?: string | null; request?: unknown }, actorId: string, action?: string): Promise<AdminBooking | undefined>; listBookingEvents(id: string): Promise<BookingEvent[]>; addBookingEvent(input: { bookingId: string; actorId?: string; action: string; fromStatus?: BookingStatus; toStatus?: BookingStatus; note?: string }): Promise<BookingEvent>;
  listTours(filters?: TourFilters): Promise<Tour[]>; findTour(idOrSlug: string): Promise<Tour | undefined>; createTour(input: CreateTour): Promise<Tour>; updateTour(id: string, patch: UpdateTour): Promise<Tour | undefined>; archiveTour(id: string): Promise<Tour | undefined>; tourStats(): Promise<{ total: number; published: number; draft: number; archived: number }>;
  createPayment(input: CreatePayment): Promise<Payment>; updatePayment(id: string, patch: Partial<Pick<Payment, 'status' | 'transactionRef' | 'providerPayload'>>): Promise<Payment | undefined>; listAdminPayments(filters?: { q?: string; status?: PaymentStatus | 'all'; provider?: string; page?: number; pageSize?: number }): Promise<{ payments: AdminPayment[]; total: number; page: number; pageSize: number; pageCount: number }>;
  createSupportTicket(input: CreateTicket): Promise<SupportTicket>; listSupportTickets(filters?: { status?: SupportTicket['status'] | 'all'; q?: string }): Promise<SupportTicket[]>; updateSupportTicket(id: string, patch: { status?: SupportTicket['status']; priority?: SupportPriority; assignedTo?: string | null }): Promise<SupportTicket | undefined>; findSupportTicket(id: string): Promise<SupportTicket | undefined>; listSupportMessages(ticketId: string): Promise<SupportMessage[]>; createSupportMessage(input: Omit<SupportMessage, 'id' | 'createdAt'>): Promise<SupportMessage>;
  getSetting(key: string): Promise<string | undefined>; getAdminSettings(): Promise<AdminSetting[]>; updateSettings(patch: SettingPatch, updatedBy: string): Promise<void>; getServiceVisibility(): Promise<ServiceVisibility[]>; updateServiceVisibility(key: ServiceKey, status: ServiceStatus, updatedBy: string): Promise<ServiceVisibility>;
  createNotification(input: CreateNotification): Promise<Notification>; findNotification(id: string): Promise<AdminNotification | undefined>; updateNotificationDelivery(id: string, patch: { status: NotificationStatus; sentAt?: string; failureReason?: string }): Promise<Notification | undefined>; listNotifications(userId: string): Promise<Notification[]>; markNotificationRead(id: string, userId: string): Promise<Notification | undefined>; listAdminNotifications(filters?: { q?: string; status?: NotificationStatus | 'all'; page?: number; pageSize?: number }): Promise<{ notifications: AdminNotification[]; total: number; page: number; pageSize: number; pageCount: number }>;
  listContent(filters?: ContentFilters): Promise<ContentItem[]>; findContent(id: string): Promise<ContentItem | undefined>; createContent(input: CreateContent): Promise<ContentItem>; updateContent(id: string, patch: UpdateContent): Promise<ContentItem | undefined>; archiveContent(id: string): Promise<ContentItem | undefined>; deleteContent(id: string): Promise<boolean>;
  listTravelAgents(filters?: { q?: string; status?: TravelAgentStatus | 'all'; department?: string; featured?: boolean; page?: number; pageSize?: number; publicOnly?: boolean }): Promise<{ agents: TravelAgent[]; total: number; page: number; pageSize: number; pageCount: number }>; findTravelAgent(id: string): Promise<TravelAgent | undefined>; createTravelAgent(input: Omit<TravelAgent,'id'|'createdAt'|'updatedAt'>): Promise<TravelAgent>; updateTravelAgent(id: string, patch: Partial<Omit<TravelAgent,'id'|'createdAt'|'updatedAt'>>): Promise<TravelAgent | undefined>; archiveTravelAgent(id: string): Promise<TravelAgent | undefined>; deleteTravelAgent(id: string): Promise<boolean>; createMediaAsset(input: CreateMediaAsset): Promise<MediaAsset>; findMediaAsset(id: string): Promise<MediaAsset | undefined>; listMediaAssets(filters?: { q?: string; folder?: string; status?: MediaStatus | 'all'; page?: number; pageSize?: number }): Promise<{ media: MediaAsset[]; total: number; page: number; pageSize: number; pageCount: number }>; updateMediaAsset(id: string, patch: Partial<Pick<MediaAsset, 'altText' | 'status' | 'secureUrl' | 'publicId' | 'width' | 'height' | 'bytes' | 'format' | 'originalFilename' | 'mimeType' | 'folder'>>): Promise<MediaAsset | undefined>; mediaReferenceCount(id: string): Promise<number>;
  createCampaign(input: CreateCampaign): Promise<Campaign>; listCampaigns(filters?: { q?: string; status?: CampaignStatus | 'all'; page?: number; pageSize?: number }): Promise<{ campaigns: Campaign[]; total: number; page: number; pageSize: number; pageCount: number }>; findCampaign(id: string): Promise<Campaign | undefined>; updateCampaign(id: string, patch: UpdateCampaign): Promise<Campaign | undefined>; deleteCampaign(id: string): Promise<boolean>; queueCampaign(id: string, userIds?: string[]): Promise<Campaign | undefined>; retryCampaignFailures(id: string): Promise<Campaign | undefined>; activateDueCampaigns(): Promise<void>; listCampaignRecipients(id: string, filters?: { status?: string; page?: number; pageSize?: number }): Promise<{ recipients: CampaignQueueItem[]; total: number; page: number; pageSize: number; pageCount: number }>; listQueuedCampaignRecipients(limit?: number): Promise<CampaignQueueItem[]>; claimCampaignRecipient(id: string): Promise<CampaignQueueItem | undefined>; recoverStaleCampaignRecipients(): Promise<void>; updateCampaignRecipient(id: string, patch: { status: CampaignRecipient['status']; error?: string; providerRef?: string }): Promise<CampaignRecipient | undefined>; recalculateCampaign(id: string): Promise<Campaign | undefined>; createCampaignTemplate(input: Omit<CampaignTemplate,'id'|'createdAt'|'updatedAt'>): Promise<CampaignTemplate>; listCampaignTemplates(type?: CampaignChannel): Promise<CampaignTemplate[]>; updateCampaignTemplate(id: string, patch: Partial<Omit<CampaignTemplate,'id'|'createdAt'|'updatedAt'>>): Promise<CampaignTemplate | undefined>; createCustomerSegment(input: Omit<CustomerSegment,'id'|'createdAt'|'updatedAt'>): Promise<CustomerSegment>; listCustomerSegments(): Promise<CustomerSegment[]>; updateCustomerSegment(id: string, patch: Partial<Omit<CustomerSegment,'id'|'createdAt'|'updatedAt'>>): Promise<CustomerSegment | undefined>; estimateSegment(rules: Record<string, unknown>): Promise<number>;
  adminStats(): Promise<AdminStats>; listAuditLogs(limit?: number): Promise<Array<{ id: number; action: string; userId?: string; metadata: unknown; createdAt: string }>>; listAuditLogsDetailed(filters?: { q?: string; action?: string; page?: number; pageSize?: number }): Promise<{ logs: AdminAuditLog[]; total: number; page: number; pageSize: number; pageCount: number }>;
  audit(action: string, input: { userId?: string; ip?: string; userAgent?: string; metadata?: unknown }): Promise<void>;
}

const DEFAULT_NAVIGATION: Array<Omit<CreateNavItem,'id'>> = [
  { groupName:'Dashboard', label:'Overview', route:'/admin', icon:'grid', permission:'dashboard_view', sortOrder:10, visible:true, enabled:true },
  { groupName:'Bookings', label:'All Bookings', route:'/admin/bookings', icon:'briefcase', permission:'bookings_view', sortOrder:20, visible:true, enabled:true },
  { groupName:'Bookings', label:'Pending / Needs Review', route:'/admin/bookings?status=needs_review', icon:'clock', permission:'bookings_view', sortOrder:21, visible:true, enabled:true },
  { groupName:'Bookings', label:'Confirmed', route:'/admin/bookings?status=confirmed', icon:'check', permission:'bookings_view', sortOrder:22, visible:true, enabled:true },
  { groupName:'Bookings', label:'Cancelled', route:'/admin/bookings?status=cancelled', icon:'close', permission:'bookings_view', sortOrder:23, visible:true, enabled:true },
  { groupName:'Bookings', label:'Completed', route:'/admin/bookings?status=completed', icon:'flag', permission:'bookings_view', sortOrder:24, visible:true, enabled:true },
  { groupName:'Services', label:'Flights', route:'/admin/flights', icon:'plane', permission:'services_manage', sortOrder:30, visible:true, enabled:true },
  { groupName:'Services', label:'Hotels', route:'/admin/hotels', icon:'hotel', permission:'services_manage', sortOrder:31, visible:true, enabled:true },
  { groupName:'Services', label:'Homes', route:'/admin/homes', icon:'home', permission:'services_manage', sortOrder:32, visible:true, enabled:true },
  { groupName:'Services', label:'Visa Applications', route:'/admin/visa', icon:'passport', permission:'services_manage', sortOrder:33, visible:true, enabled:true },
  { groupName:'Services', label:'Go Get Tour', route:'/admin/tours', icon:'map', permission:'content_manage', sortOrder:34, visible:true, enabled:true },
  { groupName:'Services', label:'eSIM', route:'/admin/esim', icon:'sim', permission:'services_manage', sortOrder:35, visible:true, enabled:true },
  { groupName:'Catalogue', label:'Tour Packages', route:'/admin/tours', icon:'map', permission:'content_manage', sortOrder:40, visible:true, enabled:true },
  { groupName:'Catalogue', label:'Hotels', route:'/admin/content?type=hotel', icon:'hotel', permission:'content_manage', sortOrder:41, visible:true, enabled:true },
  { groupName:'Catalogue', label:'Destinations', route:'/admin/content?type=destination', icon:'pin', permission:'content_manage', sortOrder:42, visible:true, enabled:true },
  { groupName:'Catalogue', label:'Airlines', route:'/admin/content?type=airline', icon:'plane', permission:'content_manage', sortOrder:43, visible:true, enabled:true },
  { groupName:'Customers', label:'Customers', route:'/admin/customers', icon:'users', permission:'customers_view', sortOrder:50, visible:true, enabled:true },
  { groupName:'Customers', label:'Segments', route:'/admin/customers/segments', icon:'users', permission:'customers_view', sortOrder:51, visible:true, enabled:true },
  { groupName:'Payments', label:'Transactions', route:'/admin/payments', icon:'card', permission:'payments_view', sortOrder:60, visible:true, enabled:true },
  { groupName:'Communication', label:'Notifications', route:'/admin/notifications', icon:'bell', permission:'notifications_send', sortOrder:70, visible:true, enabled:true },
  { groupName:'Support', label:'Support Tickets', route:'/admin/support', icon:'headset', permission:'support_manage', sortOrder:80, visible:true, enabled:true },
  { groupName:'Website', label:'Homepage Content', route:'/admin/content?type=homepage', icon:'spark', permission:'content_manage', sortOrder:90, visible:true, enabled:true },
  { groupName:'Website', label:'Media Library', route:'/admin/media', icon:'image', permission:'content_manage', sortOrder:91, visible:true, enabled:true },
  { groupName:'Website', label:'Service Visibility', route:'/admin/services', icon:'eye', permission:'services_manage', sortOrder:92, visible:true, enabled:true },
  { groupName:'Settings', label:'Settings', route:'/admin/settings', icon:'settings', permission:'settings_manage', sortOrder:100, visible:true, enabled:true },
  { groupName:'Settings', label:'System Status', route:'/admin/system-status', icon:'activity', permission:'dashboard_view', sortOrder:101, visible:true, enabled:true },
  { groupName:'Security', label:'Profile & Security', route:'/admin/profile', icon:'shield', permission:'dashboard_view', sortOrder:110, visible:true, enabled:true },
  { groupName:'Security', label:'Admin Users & Roles', route:'/admin/users', icon:'lock', permission:'users_manage', sortOrder:111, visible:true, enabled:true },
  { groupName:'Security', label:'Navigation Manager', route:'/admin/navigation', icon:'menu', permission:'navigation_manage', sortOrder:112, visible:true, enabled:true },
  { groupName:'Security', label:'Audit Logs', route:'/admin/audit-logs', icon:'activity', permission:'audit_view', sortOrder:113, visible:true, enabled:true },
  { groupName:'Marketing', label:'Campaigns', route:'/admin/campaigns', icon:'megaphone', permission:'notifications_send', sortOrder:120, visible:true, enabled:true },
  { groupName:'Marketing', label:'Campaign Templates', route:'/admin/campaigns/templates', icon:'message', permission:'notifications_send', sortOrder:121, visible:true, enabled:true },
  { groupName:'People', label:'Travel Agents', route:'/admin/travel-agents', icon:'users', permission:'content_manage', sortOrder:130, visible:true, enabled:true },
  { groupName:'Offers', label:'Special Umrah Fare', route:'/admin/content?type=umrah_fare', icon:'plane', permission:'content_manage', sortOrder:140, visible:true, enabled:true },
  { groupName:'Offers', label:'Umrah Packages', route:'/admin/content?type=umrah_package', icon:'map', permission:'content_manage', sortOrder:141, visible:true, enabled:true },
  { groupName:'Offers', label:'Holiday Packages', route:'/admin/content?type=holiday_package', icon:'globe', permission:'content_manage', sortOrder:142, visible:true, enabled:true },
  { groupName:'Offers', label:'Medical Tourism', route:'/admin/content?type=medical_tourism', icon:'hospital', permission:'content_manage', sortOrder:143, visible:true, enabled:true },
  { groupName:'Offers', label:'Card Offers', route:'/admin/content?type=card_offer', icon:'card', permission:'content_manage', sortOrder:144, visible:true, enabled:true },
  { groupName:'Offers', label:'Airlines Offers', route:'/admin/content?type=airline_offer', icon:'plane', permission:'content_manage', sortOrder:145, visible:true, enabled:true },
  { groupName:'Explore', label:'Explore', route:'/admin/content?type=explore', icon:'pin', permission:'content_manage', sortOrder:150, visible:true, enabled:true },
  { groupName:'Website', label:'Sadik App', route:'/admin/content?type=app', icon:'phone', permission:'content_manage', sortOrder:151, visible:true, enabled:true }
];

/** Mongoose models: each persistent domain has its own collection and schema. */
const { Schema, model, models } = mongoose;
type DocModel = mongoose.Model<any>;
const mixed = Schema.Types.Mixed;
const makeModel = (name: string, collection: string, fields: Record<string, any>, indexes: Array<[Record<string, 1 | -1>, Record<string, any>?]> = []): DocModel => {
  if (models[name]) return models[name] as DocModel;
  const schema = new Schema({ id: { type: String, required: true, unique: true, index: true }, ...fields }, { versionKey: false, strict: true, collection });
  indexes.forEach(([keys, options]) => schema.index(keys, options));
  return model(name, schema, collection);
};
const UserModel = makeModel('SadikUser', 'users', { phone: { type: String, unique: true, sparse: true, index: true }, email: { type: String, unique: true, sparse: true, lowercase: true, index: true }, fullName: String, avatarUrl: String, avatarMediaId: String, lastLoginAt: String, lastLoginIp: String, marketingEmailOptIn: { type: Boolean, default: true }, marketingSmsOptIn: { type: Boolean, default: true }, marketingInAppOptIn: { type: Boolean, default: true }, status: { type: String, enum: ['active','blocked','pending'], index: true }, role: { type: String, enum: ['customer','manager','admin','super_admin','support','content_manager','finance'], index: true }, createdAt: { type: String, index: true }, updatedAt: String });
const OtpModel = makeModel('SadikOtp', 'otp_challenges', { identity: { type: String, index: true }, channel: { type: String, enum: ['sms','email'] }, codeHash: String, attempts: Number, maxAttempts: Number, expiresAt: { type: String, index: true }, consumedAt: String, requestIp: String, purpose: String, userId: String, targetIdentity: String, createdAt: String }, [[{ identity: 1, createdAt: -1 }]]);
const SessionModel = makeModel('SadikSession', 'sessions', { userId: { type: String, index: true }, refreshJti: { type: String, unique: true, index: true }, userAgent: String, ip: String, expiresAt: { type: String, index: true }, revokedAt: String, createdAt: String }, [[{ userId: 1, createdAt: -1 }]]);
const BookingModel = makeModel('SadikBooking', 'bookings', { userId: { type: String, index: true }, vertical: { type: String, enum: ['flight','hotel','home','visa','esim','tour'], index: true }, status: { type: String, index: true }, providerRef: String, ownerId: { type: String, index: true }, internalNote: String, request: mixed, response: mixed, createdAt: String, updatedAt: { type: String, index: true } }, [[{ status: 1, updatedAt: -1 }]]);
const BookingEventModel = makeModel('SadikBookingEvent', 'booking_events', { bookingId: { type: String, index: true }, actorId: String, action: String, fromStatus: String, toStatus: String, note: String, createdAt: String }, [[{ bookingId: 1, createdAt: 1 }]]);
const TourModel = makeModel('SadikTour', 'tours', { slug: { type: String, unique: true, index: true }, title: String, country: { type: String, index: true }, tourType: { type: String, index: true }, destinations: [String], durationDays: Number, durationNights: Number, description: String, imageUrl: String, mediaId: String, metadata: mixed, priceBdt: { type: Number, index: true }, status: { type: String, index: true }, featured: Boolean, createdBy: String, createdAt: String, updatedAt: String }, [[{ status: 1, country: 1, tourType: 1, priceBdt: 1 }]]);
const PaymentModel = makeModel('SadikPayment', 'payments', { bookingId: { type: String, index: true }, userId: { type: String, index: true }, provider: String, amount: Number, currency: String, status: { type: String, index: true }, transactionRef: String, providerPayload: mixed, createdAt: String, updatedAt: String });
const TicketModel = makeModel('SadikSupportTicket', 'support_tickets', { userId: { type: String, index: true }, name: String, mobile: String, email: String, subject: String, status: { type: String, index: true }, priority: String, assignedTo: String, createdAt: String, updatedAt: String });
const SupportMessageModel = makeModel('SadikSupportMessage', 'support_messages', { ticketId: { type: String, index: true }, authorId: String, authorType: String, message: String, internal: Boolean, createdAt: String });
const NotificationModel = makeModel('SadikNotification', 'notifications', { userId: { type: String, index: true }, title: String, message: String, channels: [String], status: { type: String, index: true }, readAt: String, sentAt: String, failureReason: String, createdBy: String, createdAt: String }, [[{ userId: 1, createdAt: -1 }]]);
const SettingModel = makeModel('SadikSetting', 'settings', { value: String, isSecret: Boolean, updatedBy: String, updatedAt: String });
const ServiceModel = makeModel('SadikService', 'service_visibility', { key: { type: String, unique: true, index: true }, label: String, icon: String, status: { type: String, index: true }, updatedBy: String, updatedAt: String });
const ContentModel = makeModel('SadikContent', 'content_items', { type: { type: String, index: true }, slug: { type: String, index: true }, title: String, subtitle: String, description: String, imageUrl: String, mediaId: String, metadata: mixed, status: { type: String, index: true }, sortOrder: Number, createdBy: String, createdAt: String, updatedAt: String }, [[{ type: 1, slug: 1 }, { unique: true }], [{ type: 1, status: 1, sortOrder: 1, updatedAt: -1 }]]);
const MediaModel = makeModel('SadikMedia', 'media_assets', { publicId: { type: String, unique: true, index: true }, secureUrl: String, originalFilename: String, mimeType: String, format: String, width: Number, height: Number, bytes: Number, folder: { type: String, index: true }, altText: String, uploadedBy: String, status: { type: String, index: true }, createdAt: String, updatedAt: String });
const NavigationModel = makeModel('SadikNavigation', 'admin_navigation', { groupName: String, parentId: String, label: String, route: String, icon: String, permission: String, sortOrder: Number, visible: Boolean, enabled: Boolean, createdAt: String, updatedAt: String }, [[{ groupName: 1, sortOrder: 1 }]]);
const AgentModel = makeModel('SadikTravelAgent', 'travel_agents', { fullName: String, agencyName: String, photoUrl: String, photoPublicId: String, mediaId: String, jobTitle: String, department: String, phone: String, whatsapp: String, email: String, officeLocation: String, city: String, shortBio: String, fullDescription: String, languages: [String], experienceYears: Number, specialization: String, workingHours: String, status: { type: String, index: true }, featured: Boolean, displayOrder: Number, createdBy: String, updatedBy: String, createdAt: String, updatedAt: String }, [[{ status: 1, featured: 1, displayOrder: 1 }]]);
const CampaignModel = makeModel('SadikCampaign', 'campaigns', { name: String, title: String, description: String, imageUrl: String, imagePublicId: String, imageMediaId: String, channels: [String], status: { type: String, index: true }, subject: String, preheader: String, senderName: String, senderEmail: String, emailHtml: String, emailText: String, smsMessage: String, webTitle: String, webMessage: String, webCtaText: String, webCtaUrl: String, cta: String, ctaUrl: String, segmentId: String, recipientFilter: mixed, scheduledAt: String, startDate: String, endDate: String, timezone: String, totalRecipients: Number, queuedCount: Number, sentCount: Number, deliveredCount: Number, failedCount: Number, readCount: Number, createdBy: String, createdAt: String, updatedAt: String });
const CampaignRecipientModel = makeModel('SadikCampaignRecipient', 'campaign_recipients', { campaignId: { type: String, index: true }, userId: { type: String, index: true }, channel: String, status: { type: String, index: true }, providerRef: String, error: String, attempts: Number, queuedAt: String, sentAt: String, deliveredAt: String, readAt: String, createdAt: String }, [[{ campaignId: 1, userId: 1, channel: 1 }, { unique: true }], [{ status: 1, createdAt: 1 }]]);
const TemplateModel = makeModel('SadikCampaignTemplate', 'campaign_templates', { name: String, type: String, subject: String, content: String, metadata: mixed, status: { type: String, index: true }, createdBy: String, createdAt: String, updatedAt: String });
const SegmentModel = makeModel('SadikCustomerSegment', 'customer_segments', { name: String, description: String, rules: mixed, status: { type: String, index: true }, createdBy: String, createdAt: String, updatedAt: String });
const CustomerNoteModel = makeModel('SadikCustomerNote', 'customer_notes', { userId: { type: String, index: true }, authorId: String, note: String, createdAt: String });
const AuditModel = makeModel('SadikAuditLog', 'audit_logs', { action: { type: String, index: true }, userId: { type: String, index: true }, ip: String, userAgent: String, metadata: mixed, createdAt: String }, [[{ createdAt: -1 }]]);
const SecretModel = makeModel('SadikUserSecret', 'user_secrets', { passwordHash: String });
const MODELS: Record<string, DocModel> = { navigation: NavigationModel, user: UserModel, 'user-secret': SecretModel, otp: OtpModel, session: SessionModel, booking: BookingModel, 'booking-event': BookingEventModel, tour: TourModel, payment: PaymentModel, ticket: TicketModel, 'support-message': SupportMessageModel, setting: SettingModel, service: ServiceModel, notification: NotificationModel, content: ContentModel, media: MediaModel, agent: AgentModel, campaign: CampaignModel, 'campaign-recipient': CampaignRecipientModel, 'campaign-template': TemplateModel, segment: SegmentModel, 'customer-note': CustomerNoteModel, audit: AuditModel };

const now = () => new Date().toISOString();
const page = (value?: number) => Math.max(1, Math.floor(value || 1));
const pageSize = (value?: number, fallback = 20) => Math.min(100, Math.max(1, Math.floor(value || fallback)));
const normalize = (value: unknown) => String(value ?? '').toLowerCase();
const contains = (value: unknown, query?: string) => !query || normalize(value).includes(normalize(query));
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value));
const clean = <T extends Record<string, any>>(value: T): T => Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined)) as T;

const SERVICE_DEFAULTS: Array<Omit<ServiceVisibility, 'updatedBy' | 'updatedAt'>> = [
  { key: 'flights', label: 'Flights', icon: 'plane', status: 'active' }, { key: 'hotels', label: 'Hotels', icon: 'hotel', status: 'active' },
  { key: 'homes', label: 'Homes', icon: 'home', status: 'active' }, { key: 'visa', label: 'Visa', icon: 'passport', status: 'active' },
  { key: 'tours', label: 'Go Get Tour', icon: 'map', status: 'active' }, { key: 'esim', label: 'eSIM', icon: 'sim', status: 'active' }
];
const SECRET_SETTING_KEYS = new Set(['payment_webhook_secret','sslcommerz_store_password','sslcommerz_api_key','bkash_app_key','bkash_app_secret','bkash_username','bkash_password','bkash_token','sms_api_key','sms_gateway_username','sms_gateway_password','smtp_password','travel_provider_api_key','payment_provider_api_key']);

export class MongoStore implements Store {
  async health() { if (mongoose.connection.readyState !== 1) return false; await mongoose.connection.db?.admin().ping(); return true; }
  close() { void mongoose.disconnect(); }
  private modelFor(kind: string) { const entity = MODELS[kind]; if (!entity) throw new Error(`Unknown MongoDB entity kind: ${kind}`); return entity; }
  private async all<T>(kind: string) { const docs = await this.modelFor(kind).find({}).lean(); return docs.map(doc => { const { _id, __v, ...value } = doc as any; return clone(value) as T; }); }
  private async one<T>(kind: string, id: string) { const doc = await this.modelFor(kind).findOne({ id }).lean(); if (!doc) return undefined; const { _id, __v, ...value } = doc as any; return clone(value) as T; }
  private async insert<T extends { id: string }>(kind: string, data: T) { await this.modelFor(kind).create(clean(data)); return clone(data); }
  private async save<T extends { id: string }>(kind: string, data: T) { const doc = await this.modelFor(kind).findOneAndUpdate({ id: data.id }, { $set: clean(data) }, { new: true, runValidators: true }).lean(); if (!doc) return undefined; const { _id, __v, ...value } = doc as any; return clone(value) as T; }
  private async patch<T extends { id: string }>(kind: string, id: string, patch: Partial<T>) { const current = await this.one<T>(kind, id); if (!current) return undefined; return this.save(kind, { ...current, ...clean(patch as any) }); }
  private async remove(kind: string, id: string) { return (await this.modelFor(kind).deleteOne({ id })).deletedCount === 1; }
  private async paged<T>(items: T[], currentPage?: number, currentSize?: number) { const activePage = page(currentPage); const size = pageSize(currentSize); return { items: items.slice((activePage - 1) * size, activePage * size), total: items.length, page: activePage, pageSize: size, pageCount: Math.max(1, Math.ceil(items.length / size)) }; }

  async listNavigation(visibleOnly = false) { let items = await this.all<AdminNavItem>('navigation'); if (!items.length) { const time = now(); items = await Promise.all(DEFAULT_NAVIGATION.map(input => this.insert('navigation', { id: randomUUID(), ...input, createdAt: time, updatedAt: time }))); } return items.filter(item => !visibleOnly || (item.visible && item.enabled)).sort((a,b) => a.sortOrder - b.sortOrder || a.label.localeCompare(b.label)); }
  async createNavigation(input: CreateNavItem) { const time = now(); return this.insert('navigation', { id: randomUUID(), ...input, createdAt: time, updatedAt: time }); }
  async updateNavigation(id: string, patch: UpdateNavItem) { return this.patch<AdminNavItem>('navigation', id, { ...patch, updatedAt: now() }); }
  async deleteNavigation(id: string) { return this.remove('navigation', id); }
  async reorderNavigation(ids: string[]) { await Promise.all(ids.map((id, index) => this.updateNavigation(id, { sortOrder: index + 1 }))); }

  async findUserByIdentity(identity: string) { return (await this.all<User>('user')).find(user => user.phone === identity || user.email === identity); }
  async getPasswordHash(identity: string) { const user = await this.findUserByIdentity(identity); return user ? (await this.one<any>('user-secret', user.id))?.passwordHash : undefined; }
  async setPasswordHash(id: string, hash: string) { const secret = await this.one<any>('user-secret', id); if (secret) await this.save('user-secret', { ...secret, passwordHash: hash }); else await this.insert('user-secret', { id, passwordHash: hash }); }
  async findUserById(id: string) { return this.one<User>('user', id); }
  async updateUserProfile(id: string, patch: { fullName?: string; email?: string; phone?: string; avatarUrl?: string; avatarMediaId?: string; marketingEmailOptIn?: boolean; marketingSmsOptIn?: boolean; marketingInAppOptIn?: boolean }) { const duplicate = patch.email || patch.phone ? (await this.all<User>('user')).find(user => user.id !== id && (user.email === patch.email || user.phone === patch.phone)) : undefined; if (duplicate) throw Object.assign(new Error('Identity already in use'), { code: 11000 }); return this.patch<User>('user', id, { ...patch, updatedAt: now() }); }
  async updateLastLogin(id: string, ip?: string) { await this.patch<User>('user', id, { lastLoginAt: now(), lastLoginIp: ip, updatedAt: now() }); }
  async listSessions(userId: string) { return (await this.all<Session>('session')).filter(item => item.userId === userId && !item.revokedAt).sort((a,b) => b.createdAt.localeCompare(a.createdAt)); }
  async revokeOtherSessions(userId: string, keepSessionId: string) { await Promise.all((await this.all<Session>('session')).filter(item => item.userId === userId && item.id !== keepSessionId && !item.revokedAt).map(item => this.patch<Session>('session', item.id, { revokedAt: now() }))); }
  async listUsers() { return (await this.all<User>('user')).filter(user => user.status === 'active'); }
  async createUser(input: CreateUser) { const time = now(); const user: User = { id: randomUUID(), ...(input.channel === 'sms' ? { phone: input.identity } : { email: input.identity }), fullName: input.fullName, status: 'active', role: input.role || 'customer', marketingEmailOptIn: true, marketingSmsOptIn: true, marketingInAppOptIn: true, createdAt: time, updatedAt: time }; return this.insert('user', user); }
  async setUserRole(id: string, role: User['role']) { return this.patch<User>('user', id, { role, updatedAt: now() }); }
  async listAdminCustomers(filters: { q?: string; status?: User['status'] | 'all'; page?: number; pageSize?: number } = {}) { const users = (await this.all<User>('user')).filter(user => user.role === 'customer' && (!filters.status || filters.status === 'all' || user.status === filters.status) && (!filters.q || contains(`${user.fullName} ${user.email} ${user.phone}`, filters.q))); const bookings = await this.all<Booking>('booking'); const payments = await this.all<Payment>('payment'); const values: AdminCustomer[] = users.map(user => { const owned = bookings.filter(item => item.userId === user.id); const spent = payments.filter(item => item.userId === user.id && item.status === 'paid').reduce((sum,item) => sum + item.amount, 0); return { ...user, totalBookings: owned.length, totalSpentBdt: spent, lastActivity: [user.lastLoginAt, ...owned.map(item => item.updatedAt)].filter(Boolean).sort().at(-1) }; }).sort((a,b) => (b.lastActivity || b.createdAt).localeCompare(a.lastActivity || a.createdAt)); const result = await this.paged(values, filters.page, filters.pageSize); return { customers: result.items, ...result }; }
  async findAdminCustomer(id: string) { const user = await this.findUserById(id); if (!user || user.role !== 'customer') return undefined; const base = (await this.listAdminCustomers({ q: id, pageSize: 100 })).customers.find(item => item.id === id); if (!base) return undefined; return { ...base, bookings: (await this.all<Booking>('booking')).filter(item => item.userId === id), payments: (await this.all<Payment>('payment')).filter(item => item.userId === id), notifications: await this.listNotifications(id), supportTickets: (await this.all<SupportTicket>('ticket')).filter(item => item.userId === id), notes: await this.listCustomerNotes(id) }; }
  async addCustomerNote(input: { userId: string; authorId: string; note: string }) { return this.insert('customer-note', { id: randomUUID(), ...input, createdAt: now() }); }
  async listCustomerNotes(userId: string) { return (await this.all<CustomerNote>('customer-note')).filter(item => item.userId === userId).sort((a,b) => b.createdAt.localeCompare(a.createdAt)); }

  async createOtp(input: CreateOtp) { return this.insert('otp', { ...input, purpose: input.purpose || 'auth', createdAt: now() }); }
  async findOtp(id: string) { return this.one<OtpChallenge>('otp', id); }
  async incrementOtpAttempts(id: string) { const item = await this.one<OtpChallenge>('otp', id); return item ? this.save('otp', { ...item, attempts: item.attempts + 1 }) : undefined; }
  async consumeOtp(id: string) { const item = await this.one<OtpChallenge>('otp', id); if (item) await this.save('otp', { ...item, consumedAt: now() }); }
  async countRecentOtpRequests(identity: string, since: Date) { return (await this.all<OtpChallenge>('otp')).filter(item => item.identity === identity && new Date(item.createdAt) >= since).length; }
  async createSession(input: CreateSession) { return this.insert('session', { ...input, createdAt: now() }); }
  async findSessionById(id: string) { return this.one<Session>('session', id); }
  async findSessionByRefreshJti(jti: string) { return (await this.all<Session>('session')).find(item => item.refreshJti === jti); }
  async revokeSession(id: string) { const item = await this.one<Session>('session', id); if (item) await this.save('session', { ...item, revokedAt: now() }); }

  async createBooking(input: CreateBooking) { const time = now(); const booking: Booking = { id: randomUUID(), userId: input.userId, vertical: input.vertical, status: input.status || 'pending', request: input.request, createdAt: time, updatedAt: time }; await this.insert('booking', booking); await this.addBookingEvent({ bookingId: booking.id, actorId: booking.userId, action: 'created', toStatus: booking.status }); return booking; }
  async updateBooking(id: string, patch: Partial<Pick<Booking, 'status' | 'providerRef' | 'response' | 'internalNote'>>) { const current = await this.one<Booking>('booking', id); if (!current) return undefined; const updated = { ...current, ...clean(patch as any), updatedAt: now() }; await this.save('booking', updated); if (current.status !== updated.status || current.providerRef !== updated.providerRef) await this.addBookingEvent({ bookingId: id, action: 'provider_updated', fromStatus: current.status, toStatus: updated.status, note: updated.providerRef ? `Provider reference ${updated.providerRef}` : undefined }); return updated; }
  async findBooking(id: string, userId?: string) { const booking = await this.one<Booking>('booking', id); return booking && (!userId || booking.userId === userId) ? booking : undefined; }
  async findBookingForTracking(id: string, identity: string) { const booking = await this.one<Booking>('booking', id); const user = booking ? await this.findUserById(booking.userId) : undefined; return booking && (user?.email === identity || user?.phone === identity) ? booking : undefined; }
  async listBookings(userId: string) { return (await this.all<Booking>('booking')).filter(item => item.userId === userId).sort((a,b) => b.createdAt.localeCompare(a.createdAt)); }
  private async adminBooking(booking: Booking): Promise<AdminBooking> { return { ...booking, customer: await this.findUserById(booking.userId), owner: booking.ownerId ? await this.findUserById(booking.ownerId) : undefined }; }
  async listAdminBookings(filters: AdminBookingFilters = {}) { let items = await this.all<Booking>('booking'); if (filters.status === 'needs_review') items = items.filter(item => ['new','reviewing','pending'].includes(item.status)); else if (filters.status && filters.status !== 'all') items = items.filter(item => item.status === filters.status); if (filters.vertical && filters.vertical !== 'all') items = items.filter(item => item.vertical === filters.vertical); if (filters.ownerId) items = items.filter(item => item.ownerId === filters.ownerId); if (filters.q) { const users = await this.all<User>('user'); items = items.filter(item => { const user = users.find(entry => entry.id === item.userId); return contains(`${item.id} ${item.vertical} ${item.providerRef} ${user?.phone} ${user?.email} ${user?.fullName}`, filters.q); }); } items.sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)); const result = await this.paged(items, filters.page, filters.pageSize); return { bookings: await Promise.all(result.items.map(item => this.adminBooking(item))), ...result }; }
  async claimBooking(id: string, userId: string) { const booking = await this.one<Booking>('booking', id); if (!booking || (booking.ownerId && booking.ownerId !== userId)) return undefined; const updated = await this.save('booking', { ...booking, ownerId: userId, updatedAt: now() }); if (updated) await this.addBookingEvent({ bookingId: id, actorId: userId, action: 'claimed', note: 'Booking assigned to operator' }); return updated ? this.adminBooking(updated) : undefined; }
  async releaseBooking(id: string, userId: string, canReleaseAny = false) { const booking = await this.one<Booking>('booking', id); if (!booking || (!canReleaseAny && booking.ownerId !== userId)) return undefined; const updated = await this.save('booking', { ...booking, ownerId: undefined, updatedAt: now() }); if (updated) await this.addBookingEvent({ bookingId: id, actorId: userId, action: 'released' }); return updated ? this.adminBooking(updated) : undefined; }
  async updateAdminBooking(id: string, patch: { status?: BookingStatus; internalNote?: string; ownerId?: string | null; request?: unknown }, actorId: string, action = 'updated') { const booking = await this.one<Booking>('booking', id); if (!booking) return undefined; const updated = await this.save<Booking>('booking', { ...booking, ...(patch.status ? { status: patch.status } : {}), ...(patch.internalNote !== undefined ? { internalNote: patch.internalNote } : {}), ...(patch.request !== undefined ? { request: patch.request } : {}), ...(patch.ownerId !== undefined ? { ownerId: patch.ownerId || undefined } : {}), updatedAt: now() }); if (updated) await this.addBookingEvent({ bookingId: id, actorId, action, fromStatus: booking.status, toStatus: updated.status, note: patch.internalNote }); return updated ? this.adminBooking(updated) : undefined; }
  async listBookingEvents(id: string) { return (await this.all<BookingEvent>('booking-event')).filter(item => item.bookingId === id).sort((a,b) => a.createdAt.localeCompare(b.createdAt)); }
  async addBookingEvent(input: { bookingId: string; actorId?: string; action: string; fromStatus?: BookingStatus; toStatus?: BookingStatus; note?: string }) { return this.insert('booking-event', { id: randomUUID(), ...input, createdAt: now() }); }

  async listTours(filters: TourFilters = {}) { let items = await this.all<Tour>('tour'); if (filters.status && filters.status !== 'all') items = items.filter(item => item.status === filters.status); else if (!filters.status) items = items.filter(item => item.status === 'published'); if (filters.q) items = items.filter(item => contains(`${item.title} ${item.country} ${item.tourType} ${item.destinations.join(' ')}`, filters.q)); if (filters.country) items = items.filter(item => normalize(item.country) === normalize(filters.country)); if (filters.tourType) items = items.filter(item => normalize(item.tourType) === normalize(filters.tourType)); if (filters.maxPrice !== undefined) items = items.filter(item => item.priceBdt <= filters.maxPrice!); return items.sort((a,b) => filters.sort === 'price_asc' ? a.priceBdt - b.priceBdt : filters.sort === 'price_desc' ? b.priceBdt - a.priceBdt : b.createdAt.localeCompare(a.createdAt)); }
  async findTour(idOrSlug: string) { return (await this.all<Tour>('tour')).find(item => item.id === idOrSlug || item.slug === idOrSlug); }
  async createTour(input: CreateTour) { const time = now(); return this.insert('tour', { id: randomUUID(), ...input, createdAt: time, updatedAt: time }); }
  async updateTour(id: string, patch: UpdateTour) { const tour = await this.one<Tour>('tour', id); return tour ? this.save('tour', { ...tour, ...clean(patch as any), updatedAt: now() }) : undefined; }
  async archiveTour(id: string) { return this.updateTour(id, { status: 'archived' }); }
  async tourStats() { const rows = await this.all<Tour>('tour'); return { total: rows.length, published: rows.filter(item => item.status === 'published').length, draft: rows.filter(item => item.status === 'draft').length, archived: rows.filter(item => item.status === 'archived').length }; }

  async createPayment(input: CreatePayment) { const time = now(); return this.insert('payment', { id: randomUUID(), ...input, status: input.status || 'created', createdAt: time, updatedAt: time }); }
  async updatePayment(id: string, patch: Partial<Pick<Payment, 'status' | 'transactionRef' | 'providerPayload'>>) { const current = await this.one<Payment>('payment', id); return current ? this.save('payment', { ...current, ...clean(patch as any), updatedAt: now() }) : undefined; }
  async listAdminPayments(filters: { q?: string; status?: PaymentStatus | 'all'; provider?: string; page?: number; pageSize?: number } = {}) { let items = await this.all<Payment>('payment'); if (filters.status && filters.status !== 'all') items = items.filter(item => item.status === filters.status); if (filters.provider) items = items.filter(item => item.provider === filters.provider); if (filters.q) items = items.filter(item => contains(`${item.id} ${item.bookingId} ${item.transactionRef} ${item.provider}`, filters.q)); items.sort((a,b) => b.createdAt.localeCompare(a.createdAt)); const result = await this.paged(items, filters.page, filters.pageSize); return { payments: await Promise.all(result.items.map(async item => ({ ...item, customer: await this.findUserById(item.userId), booking: await this.findBooking(item.bookingId) }))), ...result }; }

  async createSupportTicket(input: CreateTicket) { const time = now(); return this.insert('ticket', { id: randomUUID(), ...input, status: input.status || 'open', priority: input.priority || 'normal', assignedTo: input.assignedTo, createdAt: time, updatedAt: time }); }
  async listSupportTickets(filters: { status?: SupportTicket['status'] | 'all'; q?: string } = {}) { return (await this.all<SupportTicket>('ticket')).filter(item => (!filters.status || filters.status === 'all' || item.status === filters.status) && (!filters.q || contains(`${item.id} ${item.name} ${item.email} ${item.mobile} ${item.subject}`, filters.q))).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)); }
  async updateSupportTicket(id: string, patch: { status?: SupportTicket['status']; priority?: SupportPriority; assignedTo?: string | null }) { const current = await this.one<SupportTicket>('ticket', id); return current ? this.save<SupportTicket>('ticket', { ...current, ...(patch.status ? { status: patch.status } : {}), ...(patch.priority ? { priority: patch.priority } : {}), ...(patch.assignedTo !== undefined ? { assignedTo: patch.assignedTo || undefined } : {}), updatedAt: now() }) : undefined; }
  async findSupportTicket(id: string) { const ticket = await this.one<SupportTicket>('ticket', id); if (!ticket) return undefined; return { ...ticket, assignedToName: ticket.assignedTo ? (await this.findUserById(ticket.assignedTo))?.fullName : undefined }; }
  async listSupportMessages(ticketId: string) { return (await this.all<SupportMessage>('support-message')).filter(item => item.ticketId === ticketId).sort((a,b) => a.createdAt.localeCompare(b.createdAt)); }
  async createSupportMessage(input: Omit<SupportMessage, 'id' | 'createdAt'>) { return this.insert('support-message', { id: randomUUID(), ...input, createdAt: now() }); }

  async getSetting(key: string) { const setting = await this.one<any>('setting', key); if (!setting) return undefined; return setting.isSecret ? decryptSecret(setting.value) : setting.value; }
  async getAdminSettings() { const rows = await this.all<any>('setting'); return rows.map(row => ({ key: row.id, value: row.isSecret ? undefined : row.value, configured: Boolean(row.value), masked: row.isSecret && row.value ? maskSecret(decryptSecret(row.value)) : undefined, secret: Boolean(row.isSecret), updatedBy: row.updatedBy, updatedAt: row.updatedAt })).sort((a,b) => a.key.localeCompare(b.key)); }
  async updateSettings(patch: SettingPatch, updatedBy: string) { await Promise.all(Object.entries(patch).filter(([,value]) => value !== undefined && value !== '').map(async ([key,value]) => { const existing = await this.one<any>('setting', key); const isSecret = SECRET_SETTING_KEYS.has(key); const item = { id: key, value: isSecret ? encryptSecret(value!) : value, isSecret, updatedBy, updatedAt: now() }; if (existing) await this.save('setting', item); else await this.insert('setting', item); })); }
  async getServiceVisibility() { let items = await this.all<ServiceVisibility>('service'); if (!items.length) { const time = now(); items = await Promise.all(SERVICE_DEFAULTS.map(item => this.insert('service', { id: item.key, ...item, updatedAt: time }))); } return items.sort((a,b) => a.label.localeCompare(b.label)); }
  async updateServiceVisibility(key: ServiceKey, status: ServiceStatus, updatedBy: string) { const current = (await this.getServiceVisibility()).find(item => item.key === key); const value: ServiceVisibility = { ...(current || SERVICE_DEFAULTS.find(item => item.key === key)!), key, status, updatedBy, updatedAt: now() }; return current ? (await this.save('service', { ...value, id: key })) as unknown as ServiceVisibility : this.insert('service', { ...value, id: key }) as unknown as ServiceVisibility; }

  async createNotification(input: CreateNotification) { return this.insert('notification', { id: randomUUID(), ...input, status: input.status || 'queued', sentAt: input.sentAt, failureReason: input.failureReason, createdBy: input.createdBy, createdAt: now() }); }
  async findNotification(id: string) { const item = await this.one<Notification>('notification', id); return item ? { ...item, recipient: await this.findUserById(item.userId), createdByUser: item.createdBy ? await this.findUserById(item.createdBy) : undefined } : undefined; }
  async updateNotificationDelivery(id: string, patch: { status: NotificationStatus; sentAt?: string; failureReason?: string }) { const item = await this.one<Notification>('notification', id); return item ? this.save('notification', { ...item, ...patch }) : undefined; }
  async listNotifications(userId: string) { return (await this.all<Notification>('notification')).filter(item => item.userId === userId).sort((a,b) => b.createdAt.localeCompare(a.createdAt)); }
  async markNotificationRead(id: string, userId: string) { const item = await this.one<Notification>('notification', id); return item && item.userId === userId ? this.save<Notification>('notification', { ...item, status: 'read', readAt: now() }) : undefined; }
  async listAdminNotifications(filters: { q?: string; status?: NotificationStatus | 'all'; page?: number; pageSize?: number } = {}) { let items = await this.all<Notification>('notification'); if (filters.status && filters.status !== 'all') items = items.filter(item => item.status === filters.status); if (filters.q) items = items.filter(item => contains(`${item.title} ${item.message}`, filters.q)); items.sort((a,b) => b.createdAt.localeCompare(a.createdAt)); const result = await this.paged(items, filters.page, filters.pageSize); return { notifications: await Promise.all(result.items.map(item => this.findNotification(item.id))) as AdminNotification[], ...result }; }

  async listContent(filters: ContentFilters = {}) { let items = await this.all<ContentItem>('content'); if (filters.type && filters.type !== 'all') items = items.filter(item => item.type === filters.type); if (filters.status && filters.status !== 'all') items = items.filter(item => item.status === filters.status); else if (!filters.includeArchived) items = items.filter(item => item.status !== 'archived'); if (filters.q) items = items.filter(item => contains(`${item.title} ${item.subtitle} ${item.description}`, filters.q)); return items.sort((a,b) => a.sortOrder - b.sortOrder || b.updatedAt.localeCompare(a.updatedAt)); }
  async findContent(id: string) { return this.one<ContentItem>('content', id); }
  async createContent(input: CreateContent) { const time = now(); return this.insert('content', { id: randomUUID(), ...input, createdAt: time, updatedAt: time }); }
  async updateContent(id: string, patch: UpdateContent) { const item = await this.one<ContentItem>('content', id); return item ? this.save('content', { ...item, ...clean(patch as any), updatedAt: now() }) : undefined; }
  async archiveContent(id: string) { return this.updateContent(id, { status: 'archived' }); }
  async deleteContent(id: string) { return this.remove('content', id); }

  async listTravelAgents(filters: { q?: string; status?: TravelAgentStatus | 'all'; department?: string; featured?: boolean; page?: number; pageSize?: number; publicOnly?: boolean } = {}) { let items = await this.all<TravelAgent>('agent'); if (filters.publicOnly) items = items.filter(item => item.status === 'active'); else if (filters.status && filters.status !== 'all') items = items.filter(item => item.status === filters.status); if (filters.department) items = items.filter(item => normalize(item.department) === normalize(filters.department)); if (filters.featured !== undefined) items = items.filter(item => item.featured === filters.featured); if (filters.q) items = items.filter(item => contains(`${item.fullName} ${item.jobTitle} ${item.department} ${item.email} ${item.phone}`, filters.q)); items.sort((a,b) => a.displayOrder - b.displayOrder || a.fullName.localeCompare(b.fullName)); const result = await this.paged(items, filters.page, filters.pageSize); return { agents: result.items, ...result }; }
  async findTravelAgent(id: string) { return this.one<TravelAgent>('agent', id); }
  async createTravelAgent(input: Omit<TravelAgent,'id'|'createdAt'|'updatedAt'>) { const time = now(); return this.insert('agent', { id: randomUUID(), ...input, createdAt: time, updatedAt: time }); }
  async updateTravelAgent(id: string, patch: Partial<Omit<TravelAgent,'id'|'createdAt'|'updatedAt'>>) { const item = await this.one<TravelAgent>('agent', id); return item ? this.save('agent', { ...item, ...clean(patch as any), updatedAt: now() }) : undefined; }
  async archiveTravelAgent(id: string) { return this.updateTravelAgent(id, { status: 'archived' }); }
  async deleteTravelAgent(id: string) { return this.remove('agent', id); }
  async createMediaAsset(input: CreateMediaAsset) { const time = now(); return this.insert('media', { id: randomUUID(), ...input, createdAt: time, updatedAt: time }); }
  async findMediaAsset(id: string) { return this.one<MediaAsset>('media', id); }
  async listMediaAssets(filters: { q?: string; folder?: string; status?: MediaStatus | 'all'; page?: number; pageSize?: number } = {}) { let items = await this.all<MediaAsset>('media'); if (filters.folder) items = items.filter(item => item.folder === filters.folder); if (filters.status && filters.status !== 'all') items = items.filter(item => item.status === filters.status); if (filters.q) items = items.filter(item => contains(`${item.originalFilename} ${item.altText} ${item.publicId}`, filters.q)); items.sort((a,b) => b.createdAt.localeCompare(a.createdAt)); const result = await this.paged(items, filters.page, filters.pageSize); return { media: result.items, ...result }; }
  async updateMediaAsset(id: string, patch: Partial<Pick<MediaAsset, 'altText' | 'status' | 'secureUrl' | 'publicId' | 'width' | 'height' | 'bytes' | 'format' | 'originalFilename' | 'mimeType' | 'folder'>>) { const item = await this.one<MediaAsset>('media', id); return item ? this.save('media', { ...item, ...clean(patch as any), updatedAt: now() }) : undefined; }
  async mediaReferenceCount(id: string) { const media = await this.findMediaAsset(id); const [tours,content,agents,users,campaigns] = await Promise.all([this.all<Tour>('tour'),this.all<ContentItem>('content'),this.all<TravelAgent>('agent'),this.all<User>('user'),this.all<Campaign>('campaign')]); const url = media?.secureUrl; const publicId = media?.publicId; return tours.filter(item => item.mediaId === id || (url && item.imageUrl === url)).length + content.filter(item => item.mediaId === id || (url && item.imageUrl === url)).length + agents.filter(item => item.mediaId === id || (url && item.photoUrl === url) || (publicId && item.photoPublicId === publicId)).length + users.filter(item => item.avatarMediaId === id || (url && item.avatarUrl === url)).length + campaigns.filter(item => item.imageMediaId === id || (url && item.imageUrl === url) || (publicId && item.imagePublicId === publicId)).length; }

  private async campaignUsers(filter: Record<string, unknown>, channels: CampaignChannel[] = []) { let users = (await this.all<User>('user')).filter(user => user.status === 'active' && user.role === 'customer'); const ids = Array.isArray(filter.userIds) ? filter.userIds.map(String) : []; if (ids.length) users = users.filter(user => ids.includes(user.id)); const countries = Array.isArray(filter.roles) ? filter.roles.map(String) : []; if (countries.length) users = users.filter(user => countries.includes(user.role)); if (channels.includes('email')) users = users.filter(user => Boolean(user.email) && user.marketingEmailOptIn !== false); if (channels.includes('sms')) users = users.filter(user => Boolean(user.phone) && user.marketingSmsOptIn !== false); if (channels.includes('in_app')) users = users.filter(user => user.marketingInAppOptIn !== false); return users; }
  async createCampaign(input: CreateCampaign) { const time = now(); return this.insert('campaign', { id: randomUUID(), ...input, totalRecipients: 0, queuedCount: 0, sentCount: 0, deliveredCount: 0, failedCount: 0, readCount: 0, createdAt: time, updatedAt: time }); }
  async listCampaigns(filters: { q?: string; status?: CampaignStatus | 'all'; page?: number; pageSize?: number } = {}) { let items = await this.all<Campaign>('campaign'); if (filters.status && filters.status !== 'all') items = items.filter(item => item.status === filters.status); if (filters.q) items = items.filter(item => contains(`${item.name} ${item.subject} ${item.webTitle}`, filters.q)); items.sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)); const result = await this.paged(items, filters.page, filters.pageSize); return { campaigns: result.items, ...result }; }
  async findCampaign(id: string) { return this.one<Campaign>('campaign', id); }
  async updateCampaign(id: string, patch: UpdateCampaign) { const item = await this.one<Campaign>('campaign', id); return item ? this.save('campaign', { ...item, ...clean(patch as any), updatedAt: now() }) : undefined; }
  async deleteCampaign(id: string) { await Promise.all((await this.all<CampaignRecipient>('campaign-recipient')).filter(item => item.campaignId === id).map(item => this.remove('campaign-recipient', item.id))); return this.remove('campaign', id); }
  async queueCampaign(id: string, userIds?: string[]) { const campaign = await this.one<Campaign>('campaign', id); if (!campaign) return undefined; const users = userIds?.length ? (await this.all<User>('user')).filter(user => userIds.includes(user.id)) : await this.campaignUsers(campaign.recipientFilter, campaign.channels); const existing = await this.all<CampaignRecipient>('campaign-recipient'); const eligible = users.filter(user => !existing.some(item => item.campaignId === id && item.userId === user.id)); const time = now(); for (const user of eligible) for (const channel of campaign.channels) { const optedIn = channel === 'email' ? Boolean(user.email) && user.marketingEmailOptIn !== false : channel === 'sms' ? Boolean(user.phone) && user.marketingSmsOptIn !== false : user.marketingInAppOptIn !== false; if (optedIn) await this.insert('campaign-recipient', { id: randomUUID(), campaignId: id, userId: user.id, channel, status: 'queued', attempts: 0, queuedAt: time, createdAt: time }); }
    return this.recalculateCampaign(id); }
  async retryCampaignFailures(id: string) { await Promise.all((await this.all<CampaignRecipient>('campaign-recipient')).filter(item => item.campaignId === id && item.status === 'failed').map(item => this.save('campaign-recipient', { ...item, status: 'queued', error: undefined, queuedAt: now() }))); return this.recalculateCampaign(id); }
  async activateDueCampaigns() { const current = now(); await Promise.all((await this.all<Campaign>('campaign')).filter(item => item.status === 'scheduled' && (!item.scheduledAt || item.scheduledAt <= current)).map(item => this.save('campaign', { ...item, status: 'queued', updatedAt: now() }))); }
  private async queueItem(item: CampaignRecipient): Promise<CampaignQueueItem> { return { ...item, recipient: await this.findUserById(item.userId), campaign: await this.findCampaign(item.campaignId) }; }
  async listCampaignRecipients(id: string, filters: { status?: string; page?: number; pageSize?: number } = {}) { let items = (await this.all<CampaignRecipient>('campaign-recipient')).filter(item => item.campaignId === id && (!filters.status || item.status === filters.status)); items.sort((a,b) => b.createdAt.localeCompare(a.createdAt)); const result = await this.paged(items, filters.page, filters.pageSize); return { recipients: await Promise.all(result.items.map(item => this.queueItem(item))), ...result }; }
  async listQueuedCampaignRecipients(limit = 10) { const items = (await this.all<CampaignRecipient>('campaign-recipient')).filter(item => item.status === 'queued').sort((a,b) => a.createdAt.localeCompare(b.createdAt)).slice(0, Math.max(1,limit)); return Promise.all(items.map(item => this.queueItem(item))); }
  async claimCampaignRecipient(id: string) { const item = await this.one<CampaignRecipient>('campaign-recipient', id); if (!item || item.status !== 'queued') return undefined; const result = await CampaignRecipientModel.findOneAndUpdate({ id, status: 'queued' }, { $set: { status: 'processing', attempts: item.attempts + 1 } }, { new: true }).lean(); if (!result) return undefined; const { _id, __v, ...value } = result as any; return this.queueItem(clone(value) as CampaignRecipient); }
  async recoverStaleCampaignRecipients() { const cutoff = new Date(Date.now() - 15 * 60_000).toISOString(); await Promise.all((await this.all<CampaignRecipient>('campaign-recipient')).filter(item => item.status === 'processing' && (!item.sentAt || item.sentAt < cutoff)).map(item => this.save('campaign-recipient', { ...item, status: 'queued' }))); }
  async updateCampaignRecipient(id: string, patch: { status: CampaignRecipient['status']; error?: string; providerRef?: string }) { const item = await this.one<CampaignRecipient>('campaign-recipient', id); if (!item) return undefined; const time = now(); return this.save('campaign-recipient', { ...item, ...patch, sentAt: ['sent','delivered','read'].includes(patch.status) ? item.sentAt || time : item.sentAt, deliveredAt: ['delivered','read'].includes(patch.status) ? time : item.deliveredAt, readAt: patch.status === 'read' ? time : item.readAt }); }
  async recalculateCampaign(id: string) { const campaign = await this.one<Campaign>('campaign', id); if (!campaign) return undefined; const rows = (await this.all<CampaignRecipient>('campaign-recipient')).filter(item => item.campaignId === id); const count = (status: CampaignRecipient['status']) => rows.filter(item => item.status === status).length; const remaining = count('queued') + count('processing'); const status: CampaignStatus = campaign.status === 'cancelled' ? 'cancelled' : remaining ? (campaign.status === 'processing' ? 'processing' : 'queued') : count('failed') ? 'partially_failed' : 'completed'; return this.save('campaign', { ...campaign, status, totalRecipients: rows.length, queuedCount: count('queued'), sentCount: count('sent'), deliveredCount: count('delivered'), failedCount: count('failed'), readCount: count('read'), updatedAt: now() }); }
  async createCampaignTemplate(input: Omit<CampaignTemplate,'id'|'createdAt'|'updatedAt'>) { const time = now(); return this.insert('campaign-template', { id: randomUUID(), ...input, createdAt: time, updatedAt: time }); }
  async listCampaignTemplates(type?: CampaignChannel) { return (await this.all<CampaignTemplate>('campaign-template')).filter(item => !type || item.type === type).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)); }
  async updateCampaignTemplate(id: string, patch: Partial<Omit<CampaignTemplate,'id'|'createdAt'|'updatedAt'>>) { const item = await this.one<CampaignTemplate>('campaign-template', id); return item ? this.save('campaign-template', { ...item, ...clean(patch as any), updatedAt: now() }) : undefined; }
  async createCustomerSegment(input: Omit<CustomerSegment,'id'|'createdAt'|'updatedAt'>) { const time = now(); return this.insert('segment', { id: randomUUID(), ...input, createdAt: time, updatedAt: time }); }
  async listCustomerSegments() { return (await this.all<CustomerSegment>('segment')).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)); }
  async updateCustomerSegment(id: string, patch: Partial<Omit<CustomerSegment,'id'|'createdAt'|'updatedAt'>>) { const item = await this.one<CustomerSegment>('segment', id); return item ? this.save('segment', { ...item, ...clean(patch as any), updatedAt: now() }) : undefined; }
  async estimateSegment(rules: Record<string, unknown>) { return (await this.campaignUsers(rules)).length; }

  async adminStats(): Promise<AdminStats> { const bookings = await this.all<Booking>('booking'); const statuses: BookingStatus[] = ['new','reviewing','accepted','processing','pending','confirmed','completed','rejected','cancelled','failed']; const counts = Object.fromEntries(statuses.map(status => [status, bookings.filter(item => item.status === status).length])) as Record<BookingStatus, number>; const verticals: Booking['vertical'][] = ['flight','hotel','home','visa','esim','tour']; const verticalCounts = Object.fromEntries(verticals.map(vertical => [vertical, bookings.filter(item => item.vertical === vertical).length])) as Record<Booking['vertical'], number>; const payments = await this.all<Payment>('payment'); const revenueBdt = payments.filter(item => item.status === 'paid' && item.currency === 'BDT').reduce((sum,item) => sum + item.amount, 0); const months = new Map<string,{revenueBdt:number;payments:number}>(); payments.forEach(item => { const key=item.createdAt.slice(0,7); const value=months.get(key)||{revenueBdt:0,payments:0}; value.payments++; if(item.status==='paid'&&item.currency==='BDT') value.revenueBdt+=item.amount; months.set(key,value); }); const tickets = await this.all<SupportTicket>('ticket'); const supportTickets = { total:tickets.length,open:tickets.filter(i=>i.status==='open').length,pending:tickets.filter(i=>i.status==='pending').length,inProgress:tickets.filter(i=>i.status==='in_progress').length,waitingCustomer:tickets.filter(i=>i.status==='waiting_customer').length,resolved:tickets.filter(i=>i.status==='resolved').length,closed:tickets.filter(i=>i.status==='closed').length }; return { bookings:{total:bookings.length,...counts}, verticalCounts, revenueBdt, revenueTrend:[...months.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([month,value])=>({month,...value})), customers:(await this.all<User>('user')).filter(item=>item.role==='customer'&&item.status==='active').length, tours:await this.tourStats(), supportTickets, statusDistribution:statuses.map(status=>({status,count:counts[status]})).filter(item=>item.count>0) }; }
  async listAuditLogs(limit = 30) { return (await this.all<any>('audit')).sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0,Math.min(100,Math.max(1,limit))).map(item => ({ id:Number(item.id), action:item.action, userId:item.userId, metadata:item.metadata, createdAt:item.createdAt })); }
  async listAuditLogsDetailed(filters: { q?: string; action?: string; page?: number; pageSize?: number } = {}) { let items = await this.all<any>('audit'); if(filters.action) items=items.filter(item=>contains(item.action,filters.action)); if(filters.q) items=items.filter(item=>contains(`${item.action} ${item.ip} ${JSON.stringify(item.metadata)}`,filters.q)); items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); const result=await this.paged(items,filters.page,filters.pageSize); return { logs:await Promise.all(result.items.map(async item=>({id:Number(item.id),action:item.action,userId:item.userId,admin:item.userId?await this.findUserById(item.userId):undefined,ip:item.ip,metadata:item.metadata,createdAt:item.createdAt}))), ...result }; }
  async audit(action: string, input: { userId?: string; ip?: string; userAgent?: string; metadata?: unknown }) { const id = String(Date.now() * 1000 + Math.floor(Math.random() * 1000)); await this.insert('audit', { id, action, ...input, createdAt: now() }); }
}

export function connectMongo() { if (!config.mongoUri) throw new Error('MONGODB_URI is required'); mongoose.set('strictQuery', true); return mongoose.connect(config.mongoUri, { serverSelectionTimeoutMS: 8_000, maxPoolSize: 20, minPoolSize: config.isProduction ? 2 : 0, autoIndex: !config.isProduction }); }
export function createStore(): { store: Store; connection: Promise<typeof mongoose> } { const store = new MongoStore(); const connection = connectMongo().then(async mongo => { await Promise.all(Object.values(MODELS).map(model => model.createIndexes())); await store.listNavigation(); await store.getServiceVisibility(); return mongo; }); return { store, connection }; }
